export const TRANSLATIONS = {
  ua: {
    header: "Cossacks Активності",
    gmt: "GMT +3",
    attack: "АТАКА",
    defense: "ОБОРОНА",
    epic: "ЕПІК РБ",
    boss: "РЕЙД БОС",
    training: "ЗБІР",
    olympiad: "ОЛІМПІАДА",
    serverTime: "Серверний час",
    kievTime: "Київський час",
    days: {
      mon: "ПОНЕДІЛОК",
      tue: "ВІВТОРОК",
      wed: "СЕРЕДА",
      thu: "ЧЕТВЕР",
      fri: "П’ЯТНИЦЯ",
      sat: "СУБОТА",
      sun: "НЕДІЛЯ",
    },
  },
  en: {
    header: "Cossacks Activities",
    gmt: "GMT +3",
    attack: "ATTACK",
    defense: "DEFENSE",
    epic: "EPIC BOSS",
    boss: "RAID BOSS",
    training: "MEETING",
    olympiad: "OLYMPIAD",
    serverTime: "Server Time",
    kievTime: "Kyiv Time",
    days: {
      mon: "MONDAY",
      tue: "TUESDAY",
      wed: "WEDNESDAY",
      thu: "THURSDAY",
      fri: "FRIDAY",
      sat: "SATURDAY",
      sun: "SUNDAY",
    },
  },
};
